# Generated by Django 2.2.4 on 2021-04-29 08:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 8, 17, 56, 951999)),
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='app_one.User')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_wish', to='app_one.User')),
                ('liked_by', models.ManyToManyField(related_name='liked_wish', to='app_one.User')),
            ],
        ),
    ]
