# Generated by Django 2.2.4 on 2021-04-29 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20210429_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 9, 9, 47, 900104)),
        ),
        migrations.AlterField(
            model_name='wish',
            name='granted_by',
            field=models.BooleanField(default=False),
        ),
    ]
